#!/usr/bin/env bash

${HOME}/.screenlayout/$(hostname).sh "br"

pgrep -x sxhkd > /dev/null || sxhkd &

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    pgrep -x polybar > /dev/null || MONITOR=$m polybar -q main -c "$HOME/.config/polybar/config.ini" &
  done
else
  polybar --reload example &
fi

pgrep -x slack > /dev/null || slack &

pgrep -x discord > /dev/null || discord &

pgrep -x dunst > /dev/null || dunst &

# pgrep -x snapclient > /dev/null || snapclient &

pgrep barriers > /dev/null || /usr/bin/barriers -f --no-tray --debug INFO --name cool-curie --enable-crypto --address :24800 &

bspc config border_width         1
bspc config window_gap          23

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color '#000000'

bspc rule --add kitty state=floating
bspc rule --add zoom state=floating
bspc rule --add Brave-browser desktop=browser
bspc rule --add Lens desktop=lens
bspc rule --add discord desktop=discord 
bspc rule --add Slack desktop=slack
bspc rule --add Zathura state=tiled
