#! /bin/sh

# ~/.screenlayout/dual.sh

MOOD="nature"

pgrep -x sxhkd > /dev/null || sxhkd &

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar -q main -c "$HOME/.config/polybar/config.ini" &
  done
else
  polybar --reload example &
fi

feh --randomize --bg-fill ${HOME}/.wallpapers/${MOOD}/ 

pgrep -x picom > /dev/null || picom &

pgrep -x dunst > /dev/null || dunst &

pgrep -x snapclient > /dev/null || snapclient &

pgrep barriers > /dev/null || /usr/bin/barriers -f --no-tray --debug INFO --name cool-curie --enable-crypto --address :24800 &

case "$( mons | grep -wc enabled )" in
  1) bspc monitor %DP-0.8 -d sh browser code slack discord lens 1 2 3 4 5
  ;;
  2) bspc monitor %DP-0.1.8 -d sh browser code empty1 empty2 lens && bspc monitor %DP-0.8 -d slack discord 1 2 3
  ;;
  *) echo default
  ;;
esac

bspc config border_width         1
bspc config window_gap          23

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color '#000000'

bspc rule -a kitty state=floating
bspc rule -a zoom state=floating
